apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-data
  namespace: rps-test

spec:
  accessModes:
    - ReadWriteOnce
  volumeName: postgres-pv
  storageClassName: ""

  resources:
    requests:
      storage: 5Gi