name: Report Service CI

on:
  push:
    branches:
      - main
    paths:
      - "report-service/**"
      - ".github/workflows/report-service.yml"

permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./report-service
          file: ./report-service/Dockerfile
          push: true
          tags: ghcr.io/freqj/rps-test:${{ github.sha }}
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Deploy Report Service
        run: |
          kubectl -n rps-test set image deployment/report-service \
            report-service=ghcr.io/freqj/rps-test:${{ github.sha }}

          kubectl -n rps-test rollout status deployment/report-service \
            --timeout=120s